In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
# Load dataset
file_path = 'Cleaned_Steam_Dataset.xlsx'
data = pd.read_excel(file_path)

In [3]:
# Selecting relevant columns for analysis
data_subset = data[['Net Revenue (in million $)', 'User Ratings']]

In [4]:
# Weights
weights = [0.5, 0.5]  # Adjust these weights as needed for importance


In [9]:
# Standardize numeric features
scaler = StandardScaler()
data_subset[['Net Revenue (in million $)', 'User Ratings']] = scaler.fit_transform(
    data_subset[['Net Revenue (in million $)', 'User Ratings']]
)

/var/folders/xv/wq7mr3g17qv81kq0q5kclg1w0000gn/T/ipykernel_2360/857227133.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_subset[['Net Revenue (in million $)', 'User Ratings']] = scaler.fit_transform(


In [11]:
# Function to calculate weighted Euclidean distance
def weighted_euclidean_distance(x, y, weights):
    squared_diff = [(xi - yi) ** 2 * w for xi, yi, w in zip(x, y, weights)]
    return np.sqrt(sum(squared_diff))

In [13]:
# Calculate the dissimilarity matrix using weighted Euclidean distance
dissimilarity_matrix = np.zeros((len(data_subset), len(data_subset)))
for i in range(len(data_subset)):
    for j in range(len(data_subset)):
        x = data_subset.iloc[i, 1:].values  # Exclude 'Title'
        y = data_subset.iloc[j, 1:].values  # Exclude 'Title'
        dissimilarity_matrix[i][j] = weighted_euclidean_distance(x, y, weights)


In [14]:
# Display the dissimilarity matrix
print(dissimilarity_matrix)

[[0.         0.         0.         ... 1.99093866 1.49320399 1.49320399]
 [0.         0.         0.         ... 1.99093866 1.49320399 1.49320399]
 [0.         0.         0.         ... 1.99093866 1.49320399 1.49320399]
 ...
 [1.99093866 1.99093866 1.99093866 ... 0.         0.49773466 0.49773466]
 [1.49320399 1.49320399 1.49320399 ... 0.49773466 0.         0.        ]
 [1.49320399 1.49320399 1.49320399 ... 0.49773466 0.         0.        ]]


In [15]:
# Create a heatmap for the dissimilarity matrix
sns.heatmap(
    dissimilarity_matrix,
    annot=False,
    cmap="YlGnBu",
    xticklabels=data_subset['Title'],
    yticklabels=data_subset['Title']
)
plt.title("Weighted Dissimilarity Matrix")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.show()

KeyError: 'Title'